"""Turning a plan into something a simulator will run — §8.32.

Both targets drive the same handshakes, and both derive them from the pack rather
than from knowledge of any particular protocol: a transaction names a starting
channel, an optional body channel and a closing one, and a channel names its
`valid`, its `ready` and its payload. The initiator asserts valid on the first
two and waits for ready; on the last it asserts ready and waits for valid. That
is the whole protocol, and it is what makes this work for a pack nobody has
written yet.

Signal *direction* is not inferred from the protocol at all — it is read off the
design. Whatever the DUT declares as an input, the testbench drives; whatever it
declares as an output, the testbench reads. There is nothing to get wrong.
"""

from __future__ import annotations

from typing import Any

from veritrace import licensing
from veritrace.protocol.model import Interface
from veritrace.protocol.pack import Channel, Pack, Transaction
from veritrace.stim.model import Plan

TARGETS = ("sv", "cocotb")


def _channels(pack: Pack) -> dict[str, Channel]:
    return {c.name: c for c in pack.channels}


def _phases(pack: Pack, txn: Transaction) -> tuple[list[Channel], Channel | None]:
    """The channels the initiator drives, and the one it waits on."""
    by = _channels(pack)
    drive = [by[txn.start]] if txn.start in by else []
    if txn.body and txn.body.channel in by:
        drive.append(by[txn.body.channel])
    end = by.get(txn.end.channel) if txn.end else None
    return drive, end


def _leaf(iface: Interface, name: str) -> str:
    """A pack-relative signal name, as the design spells it."""
    path = iface.signals.get(name)
    return path.rsplit(".", 1)[-1] if path else name


def render(
    plan: Plan,
    pack: Pack,
    iface: Interface,
    dut: Any,
    target: str = "sv",
    module: str = "vt_stim_tb",
    dump: str = "dump.vcd",
    period: int = 10,
) -> str:
    if target not in TARGETS:
        raise ValueError(f"unknown target {target!r}; try one of {', '.join(TARGETS)}")
    return (_sv if target == "sv" else _cocotb)(plan, pack, iface, dut, module, dump, period)


# --- SystemVerilog ----------------------------------------------------------


def _decl(p: Any) -> str:
    vec = "" if p.width <= 1 else f"[{p.width - 1}:0] "
    return f"  logic {vec}{p.name};"


def _sv(plan, pack, iface, dut, module, dump, period) -> str:
    clock = (iface.clock or "clk").rsplit(".", 1)[-1]
    reset = (iface.reset or "rst_n").rsplit(".", 1)[-1]
    inputs = {p.name for p in dut.ports if p.direction == "input"}

    out = [
        "`timescale 1ns / 1ps",
        "",
        f"// Generated by VeriTrace — §8.32. {len(plan.items)} transaction(s) from",
        f"// {plan.pack}, seed {plan.seed}.",
        *licensing.banner(),
        "//",
        "// The first few exist to close named coverage holes; the rest are random",
        "// draws from the same field domains, so the run still exercises the",
        "// interface and not only its corners.",
        f"module {module};",
        *(_decl(p) for p in dut.ports),
        "",
        f"  always #{period // 2} {clock} = ~{clock};",
        "",
    ]
    if dut.parameters:
        out += [
            f"  {dut.module} #(",
            ",\n".join(f"    .{n}({v})" for n, v in dut.parameters),
            "  ) dut (",
        ]
    else:
        out.append(f"  {dut.module} dut (")
    out += [
        ",\n".join(f"    .{p.name}({p.name})" for p in dut.ports),
        "  );",
        "",
    ]

    for txn in pack.transactions:
        out += _sv_task(pack, iface, txn, clock, inputs)

    out += [
        "  initial begin",
        f'    $dumpfile("{dump}");',
        f"    $dumpvars(0, {module});",
        f"    {clock} = 1'b0;",
        f"    {reset} = 1'b0;",
        *(
            f"    {_leaf(iface, ch.ready)} = 1'b0;"
            for txn in pack.transactions
            for ch in [_phases(pack, txn)[1]]
            if ch is not None and _leaf(iface, ch.ready) in inputs
        ),
        *(
            f"    {_leaf(iface, ch.valid)} = 1'b0;"
            for txn in pack.transactions
            for ch in _phases(pack, txn)[0]
            if _leaf(iface, ch.valid) in inputs
        ),
        f"    repeat (4) @(posedge {clock});",
        f"    {reset} = 1'b1;",
        f"    @(posedge {clock});",
        "",
    ]
    for item in plan.items:
        txn = next((t for t in pack.transactions if t.name == item.kind), None)
        if txn is None:
            continue
        args = ", ".join(
            f"{plan.widths.get(f, 1)}'h{item.values[f]:x}" for f in _args(pack, iface, txn, inputs)
        )
        note = f"  // {item.targets}" if item.targets else ""
        out.append(f"    vt_{txn.name.lower()}({args});{note}")
    out += [
        "",
        f"    repeat (8) @(posedge {clock});",
        f'    $display("vt_stim: {len(plan.items)} transaction(s) driven");',
        "    $finish;",
        "  end",
        "",
        "  // A DUT that never answers must not hang the run.",
        "  initial begin",
        f"    #{period * (len(plan.items) + 8) * 64};",
        '    $display("vt_stim: TIMED OUT");',
        "    $finish;",
        "  end",
        "endmodule",
        "",
    ]
    return "\n".join(out)


def _args(pack: Pack, iface: Interface, txn: Transaction, inputs: set[str]) -> list[str]:
    """Payload fields of this transaction that the testbench actually drives."""
    drive, _ = _phases(pack, txn)
    return [f for ch in drive for f in ch.payload if _leaf(iface, f) in inputs]


def _sv_task(pack, iface, txn, clock, inputs) -> list[str]:
    drive, end = _phases(pack, txn)
    fields = _args(pack, iface, txn, inputs)
    widths = {f: 32 for f in fields}
    ports = ", ".join(f"input [{widths[f] - 1}:0] {f}_i" for f in fields) or ""

    out = [f"  task automatic vt_{txn.name.lower()}({ports});", "    begin"]
    flags = [f"{ch.name.lower()}_ok" for ch in drive]
    out += [f"      bit {', '.join(flags)};" if flags else ""]
    out += [f"      {f} = 1'b0;" for f in flags]
    for ch in drive:
        out.append(f"      {_leaf(iface, ch.valid)} <= 1'b1;")
        for f in ch.payload:
            if _leaf(iface, f) in inputs:
                out.append(f"      {_leaf(iface, f)} <= {f}_i;")
    if drive:
        out += [
            f"      while (!({' && '.join(flags)})) begin",
            f"        @(posedge {clock});",
        ]
        for ch, flag in zip(drive, flags):
            v, r = _leaf(iface, ch.valid), _leaf(iface, ch.ready)
            out += [
                f"        if ({v} && {r}) begin",
                f"          {v} <= 1'b0;",
                f"          {flag} = 1'b1;",
                "        end",
            ]
        out.append("      end")
    if end is not None and _leaf(iface, end.ready) in inputs:
        v, r = _leaf(iface, end.valid), _leaf(iface, end.ready)
        out += [
            f"      {r} <= 1'b1;",
            f"      do @(posedge {clock}); while (!{v});",
            f"      {r} <= 1'b0;",
        ]
    out += ["    end", "  endtask", ""]
    return [line for line in out if line != ""] + [""]


# --- cocotb -----------------------------------------------------------------


def _cocotb(plan, pack, iface, dut, module, dump, period) -> str:
    clock = (iface.clock or "clk").rsplit(".", 1)[-1]
    reset = (iface.reset or "rst_n").rsplit(".", 1)[-1]
    inputs = {p.name for p in dut.ports if p.direction == "input"}

    out = [
        # SPDX first, where every scanner looks for it in a Python file.
        *licensing.banner("#"),
        "",
        '"""Generated by VeriTrace — §8.32.',
        "",
        f"{len(plan.items)} transaction(s) from {plan.pack}, seed {plan.seed}. Run with",
        "any simulator cocotb supports — Icarus, Verilator, ModelSim, xsim:",
        "",
        f"    make SIM=icarus TOPLEVEL={dut.module} MODULE={module}",
        '"""',
        "",
        "import cocotb",
        "from cocotb.clock import Clock",
        "from cocotb.triggers import RisingEdge",
        "",
        "",
    ]
    for txn in pack.transactions:
        out += _cocotb_task(pack, iface, txn, clock, inputs)

    out += [
        "@cocotb.test()",
        "async def stimulus(dut):",
        f'    cocotb.start_soon(Clock(dut.{clock}, {period}, units="ns").start())',
        f"    dut.{reset}.value = 0",
    ]
    for txn in pack.transactions:
        drive, end = _phases(pack, txn)
        for ch in drive:
            if _leaf(iface, ch.valid) in inputs:
                out.append(f"    dut.{_leaf(iface, ch.valid)}.value = 0")
        if end is not None and _leaf(iface, end.ready) in inputs:
            out.append(f"    dut.{_leaf(iface, end.ready)}.value = 0")
    out += [
        "    for _ in range(4):",
        f"        await RisingEdge(dut.{clock})",
        f"    dut.{reset}.value = 1",
        f"    await RisingEdge(dut.{clock})",
        "",
    ]
    for item in plan.items:
        txn = next((t for t in pack.transactions if t.name == item.kind), None)
        if txn is None:
            continue
        args = ", ".join(
            f"0x{item.values[f]:x}" for f in _args(pack, iface, txn, inputs)
        )
        note = f"  # {item.targets}" if item.targets else ""
        out.append(f"    await {txn.name.lower()}(dut, {args}){note}")
    out += [
        "",
        "    for _ in range(8):",
        f"        await RisingEdge(dut.{clock})",
        f'    dut._log.info("vt_stim: {len(plan.items)} transaction(s) driven")',
        "",
    ]
    return "\n".join(out)


def _cocotb_task(pack, iface, txn, clock, inputs) -> list[str]:
    drive, end = _phases(pack, txn)
    fields = _args(pack, iface, txn, inputs)
    out = [f"async def {txn.name.lower()}(dut, {', '.join(fields)}):"]
    for ch in drive:
        out.append(f"    dut.{_leaf(iface, ch.valid)}.value = 1")
        for f in ch.payload:
            if _leaf(iface, f) in inputs:
                out.append(f"    dut.{_leaf(iface, f)}.value = {f}")
    if drive:
        out += [
            "    pending = {" + ", ".join(f'"{ch.name}"' for ch in drive) + "}",
            "    while pending:",
            f"        await RisingEdge(dut.{clock})",
        ]
        for ch in drive:
            v, r = _leaf(iface, ch.valid), _leaf(iface, ch.ready)
            out += [
                f'        if "{ch.name}" in pending and dut.{v}.value and dut.{r}.value:',
                f"            dut.{v}.value = 0",
                f'            pending.discard("{ch.name}")',
            ]
    if end is not None and _leaf(iface, end.ready) in inputs:
        v, r = _leaf(iface, end.valid), _leaf(iface, end.ready)
        out += [
            f"    dut.{r}.value = 1",
            "    while True:",
            f"        await RisingEdge(dut.{clock})",
            f"        if dut.{v}.value:",
            "            break",
            f"    dut.{r}.value = 0",
        ]
    return out + ["", ""]
