"""Run a simulation, so that pointing VeriTrace at a folder is enough.

§4.0 is blunt that nobody reads documentation for simulator flags and that the
flags are not optional. `make sim-<tool>` answers that for a project that has a
Makefile; this answers it for the first five minutes, when someone has a folder
of SystemVerilog and a question.

Two things here are not obvious and are the reason the folder-in case works at
all:

* **A testbench with no `$dumpfile` produces no waveform**, and most do not have
  one until someone needs it. Rather than editing the user's source, a tiny
  extra module is compiled alongside it, which is legal Verilog and leaves the
  tree untouched.
* **Everything lands in a work directory**, so a run leaves `sim.vvp` and a
  dump somewhere obvious and deletable instead of scattering them next to the
  RTL — but the simulation still *runs* where the user's own flow runs it, so
  that `$readmemh("program.hex")` and `+incdir+../../hdl` resolve to the same
  files they always did. Those two are separate directories on purpose, and
  conflating them is what breaks every real project's testbench.

Icarus is the only simulator driven from here on purpose. It is §4.0's primary
target, it needs no flags to keep the hierarchy, and it is the one that installs
in a minute. The other three keep their `make sim-<tool>` recipes, which is
where their flags are already right — reimplementing those in Python would be
three more places for them to drift.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path

#: Sources that already dump do not get the generated module. Matched on the
#: text because a testbench that dumps conditionally still dumps.
_DUMP_CALL = "$dumpfile"

#: Name of the module compiled in to produce a waveform when nothing else does.
#: Leading underscore so it sorts away from the design and cannot collide with
#: anything a person would write.
DUMPER_MODULE = "_veritrace_dump"


class SimulationError(RuntimeError):
    """The simulator refused, or the run produced nothing usable."""


@dataclass(slots=True)
class Result:
    dump: Path
    log: Path
    top: str
    #: True when the waveform came from the generated module rather than from
    #: the testbench's own `$dumpvars`. Worth stating: it means the dump has
    #: everything, which is right for a first look and large for a long run.
    injected: bool
    seconds: float = 0.0
    #: What the simulation printed. Carried so `triage` can be run on it
    #: without a second pass over the file.
    output: str = ""
    warnings: list[str] = field(default_factory=list)


def find_iverilog() -> tuple[str, str] | None:
    """`(iverilog, vvp)`, or `None` when Icarus is not installed.

    Windows installs Icarus outside `PATH` often enough that the usual location
    is worth one `is_file()` before giving up — the alternative is telling
    somebody to install a program they already have.
    """
    iverilog = shutil.which("iverilog")
    vvp = shutil.which("vvp")
    if iverilog and vvp:
        return iverilog, vvp
    for base in (Path("C:/iverilog/bin"), Path("/usr/local/bin"), Path("/opt/iverilog/bin")):
        a, b = base / "iverilog.exe", base / "vvp.exe"
        if a.is_file() and b.is_file():
            return str(a), str(b)
        a, b = base / "iverilog", base / "vvp"
        if a.is_file() and b.is_file():
            return str(a), str(b)
    return None


def write_dumper(work: Path, top: str, dump_name: str = "dump.vcd") -> Path:
    """The module that makes an ordinary testbench produce a waveform.

    `$dumpvars(0, <top>)` from a separate module reaches the whole design
    because `top` is a top-level instance name, so this needs no change to the
    sources and no knowledge of the hierarchy below it.
    """
    path = work / f"{DUMPER_MODULE}.sv"
    path.write_text(
        "// Generated by `veritrace run`. Not part of your design: it exists\n"
        "// only because the testbench does not call $dumpfile itself.\n"
        f"module {DUMPER_MODULE};\n"
        "  initial begin\n"
        f'    $dumpfile("{dump_name}");\n'
        f"    $dumpvars(0, {top});\n"
        "  end\n"
        "endmodule\n",
        encoding="utf-8",
    )
    return path


def _run(cmd: list[str], cwd: Path, timeout: float) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            cmd, cwd=str(cwd), capture_output=True, text=True, timeout=timeout, check=False
        )
    except subprocess.TimeoutExpired as e:
        raise SimulationError(
            f"`{Path(cmd[0]).name}` did not finish within {timeout:g}s. A testbench with no "
            "$finish runs forever; add one, or raise --timeout."
        ) from e
    except OSError as e:
        raise SimulationError(f"could not run `{cmd[0]}`: {e}") from e


def icarus(
    sources: list[Path],
    top: str,
    work: Path,
    defines: list[str] | None = None,
    incdirs: list[str] | None = None,
    timeout: float = 120.0,
    run_dir: Path | None = None,
) -> Result:
    """Compile and run with Icarus, and return where the waveform landed.

    `run_dir` is where both tools are invoked — the directory the project's own
    flow runs from. It defaults to where the first source lives. Everything a
    testbench reads at run time is relative to it: `$readmemh("program.hex")`,
    a `+incdir+../../hdl` inside a `.f` filelist, an `$fopen` of a log. Running
    somewhere else would break all three, so the *outputs* go to `work` and the
    *run* happens here.
    """
    tools = find_iverilog()
    if tools is None:
        raise SimulationError(
            "Icarus Verilog is not installed, or not on PATH.\n"
            "  Get it from https://bleyer.org/icarus (Windows) or your package "
            "manager (`apt install iverilog`, `brew install icarus-verilog`).\n"
            "  Already have a waveform? `veritrace check dump.vcd --rtl <dir>` "
            "needs no simulator."
        )
    iverilog, vvp = tools
    work = work.resolve()
    work.mkdir(parents=True, exist_ok=True)
    sources = [Path(s).resolve() for s in sources]
    here = (run_dir or (sources[0].parent if sources else Path.cwd())).resolve()

    # A `.f` file is a list of arguments, not Verilog: it is handed to the
    # compiler with `-f` and its own relative paths resolve against `run_dir`,
    # which is the whole reason that directory is a parameter. Nothing here
    # parses it — Icarus already does, and so does every other simulator, which
    # is what makes a filelist the portable way to describe a build.
    filelists = [s for s in sources if s.suffix.lower() == ".f"]
    verilog = [s for s in sources if s.suffix.lower() != ".f"]

    injected = not any(_DUMP_CALL in _read(f) for f in verilog + filelists)
    dump = work / "dump.vcd"

    started = time.perf_counter()
    vvp_path = work / "sim.vvp"
    build = [iverilog, "-g2012", "-o", str(vvp_path), "-s", top]
    if injected:
        # Both roots have to be elaborated: the design and the dumper. Naming
        # them explicitly also pins the top when the sources contain more than
        # one candidate, which is exactly when a guess would be wrong.
        build += ["-s", DUMPER_MODULE]
    # The run directory and every directory a source came from, as include
    # paths. A `.vh` next to the file that includes it is the overwhelmingly
    # common case, and `+incdir+.` is what every hand-written flow adds anyway.
    for d in _include_path(here, verilog, incdirs or []):
        build += ["-I", str(d)]
    for d in defines or []:
        build += [f"-D{d}"]
    for f in filelists:
        build += ["-f", str(f)]
    build += [str(f) for f in verilog]
    if injected:
        build.append(str(write_dumper(work, top, str(dump).replace("\\", "/"))))

    got = _run(build, here, timeout)
    if got.returncode != 0:
        raise SimulationError(_compile_error(got.stderr or got.stdout))
    warnings = [ln for ln in (got.stderr or "").splitlines() if "warning" in ln.lower()]

    ran = _run([vvp, str(vvp_path)], here, timeout)
    seconds = time.perf_counter() - started
    output = (ran.stdout or "") + (ran.stderr or "")
    log = work / "sim.log"
    log.write_text(output, encoding="utf-8")
    if ran.returncode != 0:
        raise SimulationError(f"the simulation exited {ran.returncode}:\n{_tail(output)}")

    found = dump if dump.is_file() else (_newest_dump(work) or _newest_dump(here))
    if found is None:
        raise SimulationError(
            "the simulation ran but wrote no waveform.\n"
            "  Its $dumpfile may name a path outside the work directory; pass "
            "the dump to `veritrace check` directly."
        )
    return Result(
        dump=found,
        log=log,
        top=top,
        injected=injected,
        seconds=seconds,
        output=output,
        warnings=warnings,
    )


#: A filelist line that is an option rather than a file.
_INCDIR = re.compile(r"^\+incdir\+(.*)$")
_DEFINE = re.compile(r"^\+define\+(.*)$")


def read_filelist(path: Path, seen: set[Path] | None = None) -> tuple[list[Path], list[Path], list[str]]:
    """The files, include directories and defines a `.f` names.

    The *compiler* is still handed `-f` and remains the authority on the build.
    This reads the same file for a different consumer: pyslang, which builds the
    design graph and has no notion of a command file. Two readers of one file is
    a smell; a second *opinion* would be the bug, and there is none — if this
    disagrees with Icarus about which files exist, the graph is short and the
    correlation rate says so out loud.

    Deliberately small: paths, `+incdir+`, `+define+`, comments, and nested
    `-f`. Anything else is a compiler flag and not this reader's business.
    """
    path = Path(path).resolve()
    seen = seen if seen is not None else set()
    if path in seen or not path.is_file():
        return [], [], []
    seen.add(path)

    root = path.parent
    files: list[Path] = []
    incdirs: list[Path] = []
    defines: list[str] = []
    tokens = []
    for raw in _read(path).splitlines():
        line = raw.split("//", 1)[0].split("#", 1)[0].strip()
        if line:
            tokens.extend(line.split())

    i = 0
    while i < len(tokens):
        tok = tokens[i]
        i += 1
        if m := _INCDIR.match(tok):
            incdirs += [(root / d).resolve() for d in m.group(1).split("+") if d]
        elif m := _DEFINE.match(tok):
            defines += [d for d in m.group(1).split("+") if d]
        elif tok in ("-f", "-F"):
            if i < len(tokens):
                nested = read_filelist((root / tokens[i]).resolve(), seen)
                i += 1
                files += nested[0]
                incdirs += nested[1]
                defines += nested[2]
        elif tok.startswith(("-", "+")):
            continue  # a compiler flag; Icarus reads the file itself
        else:
            files.append((root / tok).resolve())
    return files, incdirs, defines


def _include_path(here: Path, sources: list[Path], extra: list[str]) -> list[Path]:
    """Where to look for ``include`, nearest first and without duplicates."""
    out: list[Path] = [Path(d).resolve() for d in extra]
    for d in [here] + [s.parent for s in sources]:
        if d not in out:
            out.append(d)
    return out


#: Icarus says `Include file foo.vh not found`. Turning that into the flag that
#: fixes it is the difference between a wall of output and one thing to do.
_MISSING_INCLUDE = re.compile(r"Include file (\S+) not found")


def _compile_error(text: str) -> str:
    missing = sorted(set(_MISSING_INCLUDE.findall(text or "")))
    out = f"compilation failed:\n{_tail(text)}"
    if missing:
        out += (
            f"\n\n  {', '.join(missing)} is included but not on the include path.\n"
            "  Add the directory holding it:  --incdir <dir>\n"
            "  If your project already has a `.f` filelist with `+incdir+` in it, "
            "point at that instead:  veritrace run path/to/rtl.f path/to/tb.f --top <top>"
        )
    return out


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _newest_dump(work: Path) -> Path | None:
    found = [p for p in work.glob("*.vcd") if p.is_file()] + [
        p for p in work.glob("*.fst") if p.is_file()
    ]
    return max(found, key=lambda p: p.stat().st_mtime) if found else None


def _tail(text: str, lines: int = 20) -> str:
    kept = [ln for ln in text.splitlines() if ln.strip()][-lines:]
    return "\n".join("    " + ln for ln in kept)
